//HintName: SESetting.g.cs
// <autogenerated/>
using System;

namespace ShipEnhancements.Settings;

public record SESetting<T>(
    string Name,
    SESettingType SettingType,
    T Value,
    T Config
);