//HintName: SESettingType.g.cs
// <autogenerated/>
namespace ShipEnhancements.Settings;

public enum SESettingType
{
    None,
    Checkbox,
    Toggle,
    Text,
    Number,
    Selector,
    Slider,
    Separator
}