//HintName: SESettings.g.cs
// <autogenerated/>
using ShipEnhancements.Settings;

namespace GenTests.Tests;

public static partial class SESettings {

    // SETTINGS

    public static readonly SESetting<float> ThrustForce =
        new SESetting<float>("ThrustForce", SESettingType.Number, 3.6, 3.6);
    public static readonly SESetting<bool> DisableDoor =
        new SESetting<bool>("DisableDoor", SESettingType.Checkbox, false, false);
    public static readonly SESetting<int> Grav =
        new SESetting<int>("Grav", SESettingType.Slider, 4, 4);
    public static readonly SESetting<string> ErnestoNickname =
        new SESetting<string>("ErnestoNickname", SESettingType.Text, "Ernesto", "Ernesto");
}
