//HintName: SESettingAttribute.g.cs
// <autogenerated/>
using System;

namespace ShipEnhancements.Settings;

[AttributeUsage(AttributeTargets.Class, AllowMultiple=true, Inherited=false)]
public class SESettingAttribute : System.Attribute {

    public string Name { get; set; }
    public Type FieldType { get; set; }
    public SESettingType SettingType { get; set; }
    public object? DefaultValue { get; set; }
    
    public SESettingAttribute(string name, Type fieldType, SESettingType settingType,  object? defaultValue) {
        Name = name;
        FieldType = fieldType;
        SettingType = settingType;
        DefaultValue = defaultValue;
    }
}