schema = "https://raw.githubusercontent.com/Outer-Wilds-New-Horizons/new-horizons/main/NewHorizons/Schemas/dialogue_schema.xsd"
file_type = "DialogueTree"
name_field = "Ernesto"

[[dialogue_node]]
name = "SE_Ernesto_Default_1"
entry_condition = ["DEFAULT"]

[[dialogue_node.dialogue]]
page = ["Hey. It's been a while."]

[dialogue_node.dialogue_options_list]

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "Who are you?"
dialogue_target = "SE_Ernesto_Default_11"

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "What are you doing in my ship?"
dialogue_target = "SE_Ernesto_Default_12"

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "Ernesto? Is that you?"
dialogue_target = "SE_Ernesto_Default_13"

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "I really have to get going, can we talk later?"
dialogue_target = "SE_Ernesto_Default_14"



[[dialogue_node]]
name = "SE_Ernesto_Default_11"

[[dialogue_node.dialogue]]
page = ["What do you mean? Don't you remember me?"]

[dialogue_node.dialogue_options_list]

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "Uh... no?"
dialogue_target = "SE_Ernesto_Default_111"

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "Oh yeah! Ernesto!"
dialogue_target = "SE_Ernesto_Default_112"



[[dialogue_node]]
name = "SE_Ernesto_Default_111"

[[dialogue_node.dialogue]]
page = ["Wow. Did you hit your head or something?", "I'm Ernesto the Magic Talking Anglerfish. Or just Ernesto, if you prefer."]

[dialogue_node.dialogue_options_list]

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "Are you the guy who keeps attacking me in Dark Bramble?"
dialogue_target = "SE_Ernesto_Default_1111"

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "How are you talking?"
dialogue_target = "SE_Ernesto_Default_1112"



[[dialogue_node]]
name = "SE_Ernesto_Default_1111"
dialogue_target = "SE_Ernesto_Default_2"

[[dialogue_node.dialogue]]
page = ["No, that's my cousin. Or maybe it was my uncle, I don't remember."]



[[dialogue_node]]
name = "SE_Ernesto_Default_1112"
dialogue_target = "SE_Ernesto_Default_2"

[[dialogue_node.dialogue]]
page = ["I took speaking as an elective in college."]



[[dialogue_node]]
name = "SE_Ernesto_Default_112"

[[dialogue_node.dialogue]]
page = ["Glad you're finally coming to your senses. What are you gonna tell me next, that you don't remember Geswaldo?"]

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "I know who Geswaldo is!"
dialogue_target = "SE_Ernesto_Default_1121"

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "Who?"
dialogue_target = "SE_Ernesto_Default_1122"



[[dialogue_node]]
name = "SE_Ernesto_Default_1121"
dialogue_target = "SE_Ernesto_Default_2"

[[dialogue_node.dialogue]]
page = ["Good. He's gonna be on your quiz later."]



[[dialogue_node]]
name = "SE_Ernesto_Default_1122"
dialogue_target = "SE_Ernesto_Default_2"

[[dialogue_node.dialogue]]
page = ["Unbelievable. You gotta keep up with the Ernesto lore."]



[[dialogue_node]]
name = "SE_Ernesto_Default_12"

[[dialogue_node.dialogue]]
page = ["I was waiting for you to get here. You know who I am, right?"]

[dialogue_node.dialogue_options_list]

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "Yeah, you're Ernesto."
dialogue_target = "SE_Ernesto_Default_121"

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "You're a talking anglerfish."
dialogue_target = "SE_Ernesto_Default_122"



[[dialogue_node]]
name = "SE_Ernesto_Default_121"
dialogue_target = "SE_Ernesto_Default_2"

[[dialogue_node.dialogue]]
page = ["Whew. I was worried you had forgotten about me."]



[[dialogue_node]]
name = "SE_Ernesto_Default_122"
dialogue_target = "SE_Ernesto_Default_2"

[[dialogue_node.dialogue]]
page = ["Well, yeah. Close enough. I'm Ernesto the Magic Talking Anglerfish."]



[[dialogue_node]]
name = "SE_Ernesto_Default_13"

[[dialogue_node.dialogue]]
page = ["It sure is."]

[dialogue_node.dialogue_options_list]

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "Did you pay your taxes?"
dialogue_target = "SE_Ernesto_Default_131"

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "Where's Geswaldo?"
dialogue_target = "SE_Ernesto_Default_132"



[[dialogue_node]]
name = "SE_Ernesto_Default_131"
dialogue_target = "SE_Ernesto_Default_2"

[[dialogue_node.dialogue]]
page = ["No, of course not. Tax evasion is fun. And free."]



[[dialogue_node]]
name = "SE_Ernesto_Default_132"
dialogue_target = "SE_Ernesto_Default_2"

[[dialogue_node.dialogue]]
page = ["That's a long story."]



[[dialogue_node]]
name = "SE_Ernesto_Default_14"

[[dialogue_node.dialogue]]
page = ["Yeah, sure."]



[[dialogue_node]]
name = "SE_Ernesto_Default_2"

[[dialogue_node.dialogue]]
page = ["Anyway, since I've been gone for so long, I thought I'd pay you a visit. Maybe have a chat, roast a couple marshmallows, like we used to do back in the day."]

[dialogue_node.dialogue_options_list]

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "Sounds fun!"
dialogue_target = "SE_Ernesto_Default_21"

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "I'm kind of busy right now, actually."
dialogue_target = "SE_Ernesto_Default_22"



[[dialogue_node]]
name = "SE_Ernesto_Default_21"
dialogue_target = "SE_Ernesto_Default_End"

[[dialogue_node.dialogue]]
page = ["Yeah, it's pretty fun. I think I'll just relax for now, though."]



[[dialogue_node]]
name = "SE_Ernesto_Default_22"
dialogue_target = "SE_Ernesto_Default_End"

[[dialogue_node.dialogue]]
page = ["No problem, I don't wanna do anything now either. I'm just gonna sit back and relax for now."]



[[dialogue_node]]
name = "SE_Ernesto_Default_End"
set_persistent_condition = "SE_KNOWS_ERNESTO"

[[dialogue_node.dialogue]]
page = ["You do your thing, fly the ship or whatever. Just try not to kill both of us while you're at it."]



[[dialogue_node]]
name = "SE_Ernesto_Return"
entry_condition = ["SE_KNOWS_ERNESTO"]
randomize = true

[[dialogue_node.dialogue]]
page = ["What's up?"]
[[dialogue_node.dialogue]]
page = ["What? This better be important."]
[[dialogue_node.dialogue]]
page = ["You wanna ask me something?"]
[[dialogue_node.dialogue]]
page = ["Did you have a question?"]
[[dialogue_node.dialogue]]
page = ["What is it?"]
[[dialogue_node.dialogue]]
page = ["Yeah?"]
[[dialogue_node.dialogue]]
page = ["Hey."]

[dialogue_node.dialogue_options_list]

[[dialogue_node.dialogue_options_list.dialogue_option]]
required_condition = "SE_ERNESTO_OPTION_1"
text = "What's the airspeed velocity of an unladen swallow?"
dialogue_target = "SE_Ernesto_Swallow"

[[dialogue_node.dialogue_options_list.dialogue_option]]
required_condition = "SE_ERNESTO_OPTION_2"
text = "Do you play sports?"
dialogue_target = "SE_Ernesto_Sports"

[[dialogue_node.dialogue_options_list.dialogue_option]]
required_condition = "SE_ERNESTO_OPTION_3"
text = "What was it like living in Dark Bramble?"
dialogue_target = "SE_Ernesto_DarkBramble"

[[dialogue_node.dialogue_options_list.dialogue_option]]
required_condition = "SE_ERNESTO_OPTION_4"
text = "AAAH! I forgot you were in my ship!"
dialogue_target = "SE_Ernesto_Jumpscare"

[[dialogue_node.dialogue_options_list.dialogue_option]]
required_condition = "SE_ERNESTO_OPTION_5"
text = "How much do you sleep?"
dialogue_target = "SE_Ernesto_Sleeping"

[[dialogue_node.dialogue_options_list.dialogue_option]]
required_condition = "SE_ERNESTO_OPTION_6"
text = "Have you ever broken a bone?"
dialogue_target = "SE_Ernesto_BrokenBone"

[[dialogue_node.dialogue_options_list.dialogue_option]]
required_condition = "SE_ERNESTO_OPTION_7"
text = "Are you breathing at all?"
dialogue_target = "SE_Ernesto_Breathing"

[[dialogue_node.dialogue_options_list.dialogue_option]]
required_condition = "SE_ERNESTO_OPTION_8"
text = "Do you like sap wine?"
dialogue_target = "SE_Ernesto_SapWine"

[[dialogue_node.dialogue_options_list.dialogue_option]]
required_condition = "SE_ERNESTO_OPTION_9"
text = "Do you have gills or lungs?"
dialogue_target = "SE_Ernesto_Lungs"

[[dialogue_node.dialogue_options_list.dialogue_option]]
required_condition = "SE_ERNESTO_OPTION_10"
text = "Do you play any instruments?"
dialogue_target = "SE_Ernesto_Instrument"

[[dialogue_node.dialogue_options_list.dialogue_option]]
required_condition = "SE_ERNESTO_OPTION_11"
text = "Where do you live?"
dialogue_target = "SE_Ernesto_House"

[[dialogue_node.dialogue_options_list.dialogue_option]]
required_condition = "SE_ERNESTO_OPTION_12"
text = "Do you ever beat people to death with rocks?"
dialogue_target = "SE_Ernesto_Assault"

[[dialogue_node.dialogue_options_list.dialogue_option]]
required_condition = "SE_ERNESTO_OPTION_13"
text = "Why are you so small?"
dialogue_target = "SE_Ernesto_Size"

[[dialogue_node.dialogue_options_list.dialogue_option]]
required_condition = "SE_ERNESTO_OPTION_14"
text = "What's your favorite planet?"
dialogue_target = "SE_Ernesto_FavoritePlanet"

[[dialogue_node.dialogue_options_list.dialogue_option]]
required_condition = "SE_ERNESTO_OPTION_15"
text = "test"
dialogue_target = "SE_Ernesto_Picnic"

[[dialogue_node.dialogue_options_list.dialogue_option]]
required_condition = "SE_ERNESTO_OPTION_16"
text = "Can you pilot the ship for me?"
dialogue_target = "SE_Ernesto_Pilot"

[[dialogue_node.dialogue_options_list.dialogue_option]]
required_condition = "SE_ERNESTO_OPTION_17"
text = "Do you like marshmallows?"
dialogue_target = "SE_Ernesto_Marshmallows"

[[dialogue_node.dialogue_options_list.dialogue_option]]
required_condition = "SE_ERNESTO_OPTION_18"
text = "Do you have any siblings?"
dialogue_target = "SE_Ernesto_Siblings"

[[dialogue_node.dialogue_options_list.dialogue_option]]
required_condition = "SE_ERNESTO_OPTION_19"
text = "How old are you?"
dialogue_target = "SE_Ernesto_Age"

[[dialogue_node.dialogue_options_list.dialogue_option]]
required_condition = "SE_ERNESTO_OPTION_20"
text = "How fast can you fly?"
dialogue_target = "SE_Ernesto_FlyingSpeed"

[[dialogue_node.dialogue_options_list.dialogue_option]]
required_condition = "SE_ERNESTO_OPTION_21"
text = "Do you like music?"
dialogue_target = "SE_Ernesto_Music"

[[dialogue_node.dialogue_options_list.dialogue_option]]
required_condition = "SE_ERNESTO_OPTION_22"
text = "Which traveler's music is your favorite?"
dialogue_target = "SE_Ernesto_FavoriteTraveler"

# ---

[[dialogue_node.dialogue_options_list.dialogue_option]]
required_condition = "SE_ERNESTO_OPTION_100"
text = "Tell me the story of how you met Geswaldo."
dialogue_target = "SE_Ernesto_MeetingGeswaldo"

[[dialogue_node.dialogue_options_list.dialogue_option]]
required_condition = "SE_ERNESTO_OPTION_101"
text = "Can you continue your story about Geswaldo?"
dialogue_target = "SE_Ernesto_Geswaldo"

# ---

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "Nevermind."



[[dialogue_node]]
name = "SE_Ernesto_Swallow"

[[dialogue_node.dialogue]]
page = ["African or European?", "Heh, just messing with you. It's 10.4 m/s for an African swallow and 9.2 m/s for a European swallow."]



[[dialogue_node]]
name = "SE_Ernesto_Sports"

[[dialogue_node.dialogue]]
page = ["Yeah, I loved playing sports as a kid, mostly Go Fish. I was the top performing player, believe it or not."]



[[dialogue_node]]
name = "SE_Ernesto_DarkBramble"

[[dialogue_node.dialogue]]
page = ["Cold. Lonely. Scary. Damp and wet.", "I'm glad I got out of there when I did. Apparently the stock markets crashed not long after I left."]



[[dialogue_node]]
name = "SE_Ernesto_Jumpscare"

[[dialogue_node.dialogue]]
page = ["I actually have camoflauge abilities. Here, watch I'll blend into the surroundings and you'll be so surprised it worked that you'll stop talking to me."]

[dialogue_node.dialogue_options_list]

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "That doesn't-"

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "You can't-"

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "What are you-"

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "I'm confu-"



[[dialogue_node]]
name = "SE_Ernesto_Sleeping"

[[dialogue_node.dialogue]]
page = ["I don't sleep. There's too much to get done."]

[dialogue_node.dialogue_options_list]

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "What, like sitting in my cockpit doing nothing?"
dialogue_target = "SE_Ernesto_Sleeping_1"

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "Fair enough."

# ---

[[dialogue_node]]
name = "SE_Ernesto_Sleeping_1"

[[dialogue_node.dialogue]]
page = ["I'm not doing nothing, I'm gathering valuable intel.", "I probably shouldn't have said that. You didn't hear anything."]



[[dialogue_node]]
name = "SE_Ernesto_BrokenBone"

[[dialogue_node.dialogue]]
page = ["I'm an invertebrate. I don't have bones."]

[dialogue_node.dialogue_options_list]

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "But you're a fish! All fish have bones!"
dialogue_target = "SE_Ernesto_BrokenBone_1"

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "Oh, sorry."

# ---

[[dialogue_node]]
name = "SE_Ernesto_BrokenBone_1"

[[dialogue_node.dialogue]]
page = ["The \"magic\" part of \"Ernesto the Magic Talking Anglerfish\" means all my bones get taken away."]



[[dialogue_node]]
name = "SE_Ernesto_Breathing"

[[dialogue_node.dialogue]]
page = ["No, I'm holding my breath so I don't consume extra oxygen."]

[dialogue_node.dialogue_options_list]

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "Wow, you can hold your breath for a while."
dialogue_target = "SE_Ernesto_Breathing_1"

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "You can breath. My oxygen is going to be fine."
dialogue_target = "SE_Ernesto_Breathing_2"

# ---

[[dialogue_node]]
name = "SE_Ernesto_Breathing_1"

[[dialogue_node.dialogue]]
page = ["I haven't tasted oxygen in a long time."]

# ---

[[dialogue_node]]
name = "SE_Ernesto_Breathing_2"

[[dialogue_node.dialogue]]
page = ["Your ship wouldn't last a second if I started breathing. Neither would the solar system."]



[[dialogue_node]]
name = "SE_Ernesto_SapWine"

[[dialogue_node.dialogue]]
page = ["I'm convinced that stuff is poison. It tasted worse than the vines from Dark Bramble, and those things taste really bad."]



[[dialogue_node]]
name = "SE_Ernesto_Lungs"

[[dialogue_node.dialogue]]
page = ["Neither."]

[dialogue_node.dialogue_options_list]

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "I- I don't want to know."



[[dialogue_node]]
name = "SE_Ernesto_MeetingGeswaldo"

[[dialogue_node.dialogue]]
page = ["Making me dig through repressed memories, eh?", "A long time ago, I was swimming around Giant's Deep, looking at all the jellyfish floating around there. One of them caught my eye."]

[dialogue_node.dialogue_options_list]

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "Was it a particularly handsome jellyfish, by any chance?"
dialogue_target = "SE_Ernesto_MeetingGeswaldo_1"

# ---

[[dialogue_node]]
name = "SE_Ernesto_MeetingGeswaldo_1"

[[dialogue_node.dialogue]]
page = ["What? No. It was a super small jellyfish."]

[dialogue_node.dialogue_options_list]

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "Oh."
dialogue_target = "SE_Ernesto_MeetingGeswaldo_2"

# ---

[[dialogue_node]]
name = "SE_Ernesto_MeetingGeswaldo_2"

[[dialogue_node.dialogue]]
page = ["The moment I saw that jellyfish, I knew we were destined to be together.", "A tiny anglerfish kicked out of his home and a tiny jellyfish estranged to his own people. What could be a more perfect combination?"]

[dialogue_node.dialogue_options_list]

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "Marshmallows and a campfire."
dialogue_target = "SE_Ernesto_MeetingGeswaldo_21"

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "That's really sweet."
dialogue_target = "SE_Ernesto_MeetingGeswaldo_22"

# ---

[[dialogue_node]]
name = "SE_Ernesto_MeetingGeswaldo_21"

[[dialogue_node.dialogue]]
page = ["Be quiet, I'm telling a story.", "After metting Geswaldo, I knew I wanted him to be my husband. And he was, eventually. Until..."]

[dialogue_node.dialogue_options_list]

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "Until what? What happened?"
dialogue_target = "SE_Ernesto_MeetingGeswaldo_3"

# ---

[[dialogue_node]]
name = "SE_Ernesto_MeetingGeswaldo_22"

[[dialogue_node.dialogue]]
page = ["It was love at first sight. I knew I wanted to marry him the moment I looked into his eyes.", "And I did. Everything was perfect, until..."]

[dialogue_node.dialogue_options_list]

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "Until what? What happened?"
dialogue_target = "SE_Ernesto_MeetingGeswaldo_3"

# ---

[[dialogue_node]]
name = "SE_Ernesto_MeetingGeswaldo_3"
set_condition = "SE_ERNESTO_GESWALDO_PART_ONE"

[[dialogue_node.dialogue]]
page = ["It's not important. Maybe I'll tell you some other time.", "Story time's over, go fly your ship or whatever."]



[[dialogue_node]]
name = "SE_Ernesto_Instrument"

[[dialogue_node.dialogue]]
page = ["I play the vocal chords."]



[[dialogue_node]]
name = "SE_Ernesto_House"

[[dialogue_node.dialogue]]
page = [""]



[[dialogue_node]]
name = "SE_Ernesto_Assault"

[[dialogue_node.dialogue]]
page = ["Sometimes. Usually when people ask me too many questions."]



[[dialogue_node]]
name = "SE_Ernesto_Size"

[[dialogue_node.dialogue]]
page = ["I decided to adopt a no-food lifestyle when I was born, but it had some impacts on my growth."]



[[dialogue_node]]
name = "SE_Ernesto_FavoritePlanet"

[[dialogue_node.dialogue]]
page = ["My favorite planet? Probably Mars."]

[dialogue_node.dialogue_options_list]

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "Mars..?"
dialogue_target = "SE_Ernesto_FavoritePlanet_1"

# ---

[[dialogue_node]]
name = "SE_Ernesto_FavoritePlanet_1"

[[dialogue_node.dialogue]]
page = ["Oh, sorry. Ember Twin. Mars is... somewhere else."]



[[dialogue_node]]
name = "SE_Ernesto_Picnic"

[[dialogue_node.dialogue]]
page = [""]



[[dialogue_node]]
name = "SE_Ernesto_Pilot"

[[dialogue_node.dialogue]]
page = ["Yeah, sure. I don't have hands, but I should be able to use my tail.", "Do you have a flight manual?"]

[dialogue_node.dialogue_options_list]

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "Uh... no."
dialogue_target = "SE_Ernesto_Pilot_1"

# ---

[[dialogue_node]]
name = "SE_Ernesto_Pilot_1"

[[dialogue_node.dialogue]]
page = ["Oh. I can't fly it then. You Hearthians need to make your ships more user friendly."]



[[dialogue_node]]
name = "SE_Ernesto_Marshmallows"

[[dialogue_node.dialogue]]
page = ["Yeah. They're pretty good. Especially the green ones, they make me see colors."]



[[dialogue_node]]
name = "SE_Ernesto_Siblings"

[[dialogue_node.dialogue]]
page = ["Yeah, I think I have like 30 or something. Unless you count half-siblings, because then I have like 200."]



[[dialogue_node]]
name = "SE_Ernesto_Age"

[[dialogue_node.dialogue]]
page = ["Uh... 712 years, give or take a few."]

[dialogue_node.dialogue_options_list]

[[dialogue_node.dialogue_options_list.dialogue_option]]
text = "Wow. You're old."
dialogue_target = "SE_Ernesto_Age_1"

# ---

[[dialogue_node]]
name = "SE_Ernesto_Age_1"

[[dialogue_node.dialogue]]
page = ["Yeah, it's given me a lot of time to evade my taxes."]



[[dialogue_node]]
name = "SE_Ernesto_FlyingSpeed"

[[dialogue_node.dialogue]]
page = ["zoom"]



[[dialogue_node]]
name = "SE_Ernesto_Music"

[[dialogue_node.dialogue]]
page = ["Not really. It hurts my ears."]



[[dialogue_node]]
name = "SE_Ernesto_FavoriteTraveler"

[[dialogue_node.dialogue]]
page = ["I like Chert's drums. They remind me of hitting people with rocks."]