using System.Threading.Tasks.Dataflow;
using DitzyExtensions;
using DitzyExtensions.Functional;

namespace ShipEnhancements.Settings.Generator;

internal static class GenUtils
{
    public const string GenNamespace = "ShipEnhancements.Settings";
    public const string PresetsNamespace = $"{GenNamespace}.Presets";
    
    public const string SESettingSource =
        $$"""
        // <autogenerated/>
        using System;

        namespace {{GenNamespace}};

        public record SESetting<T>(
            string Name,
            string Title,
            T Value
        ) {
            public T Value { get; set; } = Value;
            public T Config { get; set; } = Value;
        }
        """;
    
    public const string SEPresetSource =
        $$"""
        // <autogenerated/>
        using System;

        namespace {{PresetsNamespace}};

        public abstract class SEPreset {
            public abstract void ApplyPreset();
        }
        """;

    public static string CreateSettingsSource(IList<SettingData> data)
    {
        return
            $$""""
            // <autogenerated/>
            using System;
            
            namespace {{GenNamespace}};
            
            public static class SESettings {
            
            {{
                data.Select(s =>
                        $"""
                        public static readonly SESetting<{s.FieldType}> {s.Name} =
                            new({s.Name.S()}, {s.Title.S()}, {s.DefaultValue});
                        """
                    )
                    .Join("\n")
                    .Indent(1)
            }}
            
                public static void ApplyConfig() {
            {{
                data.Select(s => $"{s.Name}.Value = {s.Name}.Config;")
                    .Join("\n")
                    .Indent(2)
            }}
                }
            }
            """";
    }

    public static string CreatePresetSource(
        IDictionary<string, SettingData> data,
        string presetName,
        IDictionary<string, string> presetSettings
    ) {
        return
            $$""""
            // <autogenerated/>
            using System;
            
            namespace {{PresetsNamespace}};
            
            public class {{presetName}}Preset : SEPreset {
            
            {{
                presetSettings
                    .Select(po => (s: data[po.Key], po: po.Value))
                    .Select(po =>
                        $$"""
                        public {{po.s.FieldType}} {{po.s.Name}} { get; init; } = {{po.po}};
                        """
                    )
                    .Join("\n")
                    .Indent(1)
            }}
            
                public override void ApplyPreset() {
            {{
                presetSettings
                    .Keys
                    .Select(s => $"SESettings.{s}.Config = {s};")
                    .Join("\n")
                    .Indent(2)
            }}
                }
            }
            """";
    }

    public static string S(this string s) => $"\"{s}\"";
    
    public static string PC(this string s) => s[0..1].AsUpper() + s[1..];

    private static string Indent(this string str, int level)
    {
        var indent = "    ".Repeat(level).Join("");
        return str.Split("\n")
            .Select(s => indent + s)
            .Join("\n");
    }
}