using System.Threading.Tasks.Dataflow;
using DitzyExtensions;
using DitzyExtensions.Functional;

namespace ShipEnhancements.Settings.Generator;

internal static class GenUtils
{
    public const string GenNamespace = "ShipEnhancements.Settings";
    
    public const string SESettingSource =
        $$"""
        // <autogenerated/>
        using System;

        namespace {{GenNamespace}};

        public record SESetting<T>(
            string Name,
            string Title,
            T Value
        ) {
            public T Value { get; set; } = Value;
            public T Config { get; set; } = Value;
        }
        """;

    public static string CreateSettingsSource(IList<SettingData> data)
    {
        return
            $$""""
            // <autogenerated/>
            using System;
            
            namespace {{GenNamespace}};
            
            public static class SESettings {
            
            {{
                data.Select(s =>
                        $"""
                        public static readonly SESetting<{s.FieldType}> {s.Name} =
                            new({S(s.Name)}, {S(s.Title)}, {s.DefaultValue});
                        """
                    )
                    .Join("\n")
                    .Indent(1)
            }}
            
                public static void ApplyConfig() {
            {{
                data.Select(s => $"{s.Name}.Value = {s.Name}.Config;")
                    .Join("\n")
                    .Indent(2)
            }}
                }
            }
            """";
    }

    public static string CreatePresetSource(IList<SettingData> data)
    {
        return "";
    }

    public static string S(string s) => $"\"{s}\"";

    private static string Indent(this string str, int level)
    {
        var indent = "    ".Repeat(level).Join("");
        return str.Split("\n")
            .Select(s => indent + s)
            .Join("\n");
    }
}