using System.Text;
using static DitzyExtensions.StringExtensions;

namespace ShipEnhancements.Generators;

public static class GenUtils
{
    public const string SESettingAttributeFqn = "ShipEnhancements.Settings.SESettingAttribute";
    public const string SESettingRecordFqn = "ShipEnhancements.Settings.SESetting";
    public const string GenNamespace = "ShipEnhancements.Settings";

    public const string SESettingAttributeSource =
        $$"""
        // <autogenerated/>
        using System;
        
        namespace {{GenNamespace}};
        
        [AttributeUsage(AttributeTargets.Class, AllowMultiple=true, Inherited=false)]
        public class SESettingAttribute : System.Attribute {

            public string Name { get; set; }
            public Type FieldType { get; set; }
            public SESettingType SettingType { get; set; }
            public object? DefaultValue { get; set; }
            
            public SESettingAttribute(string name, Type fieldType, SESettingType settingType,  object? defaultValue) {
                Name = name;
                FieldType = fieldType;
                SettingType = settingType;
                DefaultValue = defaultValue;
            }
        }
        """;

    public const string SESettingRecordSource =
        $$"""
        // <autogenerated/>
        using System;
        
        namespace {{GenNamespace}};
        
        public record SESetting<T>(
            string Name,
            SESettingType SettingType,
            T Value,
            T Config
        );
        """;

    public const string SESettingTypeSource =
        $$"""
        // <autogenerated/>
        namespace {{GenNamespace}};
        
        public enum SESettingType
        {
            None,
            Checkbox,
            Toggle,
            Text,
            Number,
            Selector,
            Slider,
            Separator
        }
        """;

    internal static string GetSettingsClassSource(SESettingsData data)
    {
        var targetClass = data.ClassName;
        var targetNamespace = data.Namespace;

        var sb = new StringBuilder();
        sb
            .Append(
                $$"""
                // <autogenerated/>
                using {{GenNamespace}};

                namespace {{targetNamespace}};

                public static partial class {{targetClass}} {

                """
            )
            .AppendLine()
            .AppendLine("    // SETTINGS")
            .AppendLine()
            .AppendLine(
                data
                    .Settings
                    .Values
                    .Select(s =>
                        $"""
                            public static readonly SESetting<{s.FieldType}> {s.Name} =
                                new SESetting<{s.FieldType}>("{s.Name}", SESettingType.{s.SettingType}, {s.DefaultValue}, {s.DefaultValue});
                        """
                    )
                    .Join("\n")
            )
            .AppendLine("}");

        return sb.ToString();
    }
}
